import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import { GeneratedData } from '@/types';

// Register fonts if needed. For now, we'll use standard fonts to ensure reliability
// as custom fonts require loading TTF files.
// Font.register({ family: 'Cormorant', src: '...' });

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#090909',
    color: '#F4F1EB',
    fontFamily: 'Helvetica',
  },
  coverPage: {
    padding: 40,
    backgroundColor: '#090909',
    color: '#F4F1EB',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
  coverTitle: {
    fontSize: 48,
    marginBottom: 20,
    color: '#D4A95A',
  },
  coverSubtitle: {
    fontSize: 16,
    color: '#A9A39B',
    marginBottom: 60,
  },
  timestamp: {
    fontSize: 10,
    color: '#A9A39B',
    position: 'absolute',
    bottom: 40,
  },
  sectionTitle: {
    fontSize: 24,
    color: '#D4A95A',
    marginBottom: 16,
    marginTop: 24,
    borderBottom: '1px solid #2D2D2D',
    paddingBottom: 8,
  },
  subTitle: {
    fontSize: 18,
    color: '#F4F1EB',
    marginTop: 16,
    marginBottom: 8,
  },
  text: {
    fontSize: 12,
    color: '#A9A39B',
    lineHeight: 1.5,
    marginBottom: 8,
  },
  conceptBox: {
    padding: 12,
    border: '1px solid #2D2D2D',
    backgroundColor: '#1A1A1A',
    marginBottom: 8,
    borderRadius: 4,
  },
  defTerm: {
    fontSize: 14,
    color: '#D4A95A',
    marginBottom: 4,
  },
  bulletItem: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  bulletPoint: {
    width: 10,
    fontSize: 12,
    color: '#D4A95A',
  },
  bulletText: {
    flex: 1,
    fontSize: 12,
    color: '#A9A39B',
    lineHeight: 1.5,
  },
  quizQuestion: {
    fontSize: 14,
    color: '#F4F1EB',
    marginTop: 12,
    marginBottom: 8,
  },
  quizOption: {
    fontSize: 12,
    color: '#A9A39B',
    marginLeft: 12,
    marginBottom: 4,
  },
  answerKeySection: {
    marginTop: 40,
    paddingTop: 20,
    borderTop: '1px solid #D4A95A',
  },
});

interface Props {
  data: GeneratedData;
  subject?: string;
}

export const ExportDocument = ({ data, subject = "Academic Mastery" }: Props) => (
  <Document>
    {/* Cover Page */}
    <Page size="A4" style={styles.coverPage}>
      <Text style={styles.coverTitle}>LUMINA</Text>
      <Text style={styles.coverSubtitle}>{subject}</Text>
      <Text style={styles.text}>{data.notes.chapterTitle}</Text>
      <Text style={styles.timestamp}>{new Date().toLocaleDateString()} • Generated by AI</Text>
    </Page>

    {/* Revision Notes */}
    <Page size="A4" style={styles.page}>
      <Text style={styles.sectionTitle}>Revision Notes</Text>
      
      <Text style={styles.subTitle}>Executive Summary</Text>
      <Text style={styles.text}>{data.notes.executiveSummary}</Text>

      <Text style={styles.subTitle}>Key Concepts</Text>
      {data.notes.keyConcepts.map((concept, i) => (
        <View key={i} style={styles.conceptBox}>
          <Text style={styles.text}>{concept}</Text>
        </View>
      ))}

      <Text style={styles.subTitle}>Important Definitions</Text>
      {data.notes.importantDefinitions.map((def, i) => (
        <View key={i} style={{ marginBottom: 12 }}>
          <Text style={styles.defTerm}>{def.term}</Text>
          <Text style={styles.text}>{def.definition}</Text>
        </View>
      ))}
    </Page>

    {/* More Notes & Formulas if available */}
    <Page size="A4" style={styles.page}>
      {data.notes.formulas && data.notes.formulas.length > 0 && (
        <>
          <Text style={styles.subTitle}>Core Formulas</Text>
          {data.notes.formulas.map((form, i) => (
            <View key={i} style={styles.conceptBox}>
              <Text style={styles.defTerm}>{form.name}</Text>
              <Text style={{ ...styles.text, fontStyle: 'italic' }}>{form.formula}</Text>
            </View>
          ))}
        </>
      )}

      <Text style={styles.subTitle}>Exam Focus</Text>
      {data.notes.examFocusedPoints.map((point, i) => (
        <View key={i} style={styles.bulletItem}>
          <Text style={styles.bulletPoint}>•</Text>
          <Text style={styles.bulletText}>{point}</Text>
        </View>
      ))}

      <Text style={{ ...styles.subTitle, marginTop: 24 }}>Memory Shortcuts</Text>
      {data.notes.memoryShortcuts.map((shortcut, i) => (
        <View key={i} style={styles.bulletItem}>
          <Text style={styles.bulletPoint}>★</Text>
          <Text style={styles.bulletText}>{shortcut}</Text>
        </View>
      ))}
    </Page>

    {/* Quiz & Answer Key */}
    <Page size="A4" style={styles.page}>
      <Text style={styles.sectionTitle}>Practice Quiz</Text>
      
      {data.quiz.questions.map((q, i) => (
        <View key={i} style={{ marginBottom: 16 }}>
          <Text style={styles.quizQuestion}>{i + 1}. {q.question}</Text>
          {q.options && q.options.map((opt, j) => (
            <Text key={j} style={styles.quizOption}>{String.fromCharCode(97 + j)}. {opt}</Text>
          ))}
          {q.type === 'short' && (
            <Text style={styles.quizOption}>_________________________________________________</Text>
          )}
        </View>
      ))}

      <View style={styles.answerKeySection}>
        <Text style={styles.sectionTitle}>Answer Key</Text>
        {data.quiz.questions.map((q, i) => (
          <View key={i} style={{ marginBottom: 12 }}>
            <Text style={styles.quizQuestion}>{i + 1}. Correct Answer:</Text>
            <Text style={{ ...styles.text, color: '#7FB77E' }}>{q.correctAnswer}</Text>
            <Text style={styles.text}>{q.explanation}</Text>
          </View>
        ))}
      </View>
    </Page>
  </Document>
);
